// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using DiagnosticsReleaseTool.Impl;
using System.CommandLine;
using System.CommandLine.Parsing;
using System.IO;
using System.Threading;
using System.Threading.Tasks;

namespace DiagnosticsReleaseTool.CommandLine
{
    class DiagnosticsReleaseCommandLine
    {
        static async Task<int> Main(string[] args)
        {
            var parser = new CommandLineBuilder()
                .AddCommand(PrepareRelease())
                .CancelOnProcessTermination()
                .UseDefaults()
                .Build();

            return await parser.InvokeAsync(args);
        }

        public static Command PrepareRelease() =>
            new Command(
                name: "prepare-release",
                description: "Given a darc drop, generates validated manifests and layouts to initiate a tool release.")
            {
                CommandHandler.Create<Config, bool, bool, CancellationToken>(DiagnosticsReleaseRunner.PrepareRelease),
                
                // Inputs
                InputDropPathOption(), ToolManifestPathOption(), ReleaseNameOption(), BuildVersionOption(),
                // Toggles
                ToolManifestVerificationOption(), DiagnosticLoggingOption(), DryRunOption(),
                // Outputs
                StagingPathOption(), AzureStorageAccountNameOption(), AzureStorageAccountKeyOption(), AzureStorageContainerNameOption(), AzureStorageSasExpirationOption()
            };

        private static Option<bool> DiagnosticLoggingOption() =>
            new Option<bool>(name: "verbose", aliases: new[] { "-v", "--verbose" })
            {
                Description = "Enables diagnostic logging",
                DefaultValueFactory = _ => false
            };

        private static Option<bool> DryRunOption() =>
            new Option<bool>("dry-run")
            {
                Description = "Stages files and generates manifest, but does not publish.",
                DefaultValueFactory = _ => false
            };

        private static Option ToolManifestPathOption() =>
            new Option<FileInfo>("tool-manifest",
                aliases: new[] { "-t" })

            {
                Required = true,
                Description = "Full path to the manifest of tools and packages to publish.",
            }.AcceptExistingOnly();

        private static Option<bool> ToolManifestVerificationOption() =>
            new Option<bool>(name: "verify-tool-manifest", aliases: new[] { "--verify-tool-manifest" })
            {
                Description = "Verifies that the assets being published match the manifest",
                DefaultValueFactory = _ => true
            };

        private static Option<string> ReleaseNameOption() =>
            new Option<string>(name: "release-name", aliases: new[] { "-r", "--release-name" })
            {
                Description = "Name of this release.",
                Required = true
            };

        private static Option<string> BuildVersionOption() =>
            new Option<string>(name: "build-version", aliases: new[] { "--build-version" })
            {
                Description = "Non-final version of the build.",
                Required = true
            };

        private static Option<DirectoryInfo> InputDropPathOption() =>
            new Option<DirectoryInfo>(name: "input-drop-path", aliases: new[] { "-i", "--input-drop-path" })
            {
                Description = "Path to drop generated by `darc gather-drop`",
                Required = true
            }.AcceptExistingOnly();

        private static Option<DirectoryInfo> StagingPathOption() =>
            new Option<DirectoryInfo>(name: "staging-directory", aliases: new[] { "--staging-directory", "-s" })
            {
                Description = "Full path to the staging path.",
                DefaultValueFactory = _ => new DirectoryInfo(
                    Path.Join(Path.GetTempPath(), Path.GetRandomFileName()))
            }.AcceptLegalFilePathsOnly();

        private static Option<string> AzureStorageAccountNameOption() =>
            new Option<string>(name: "account-name", aliases: new[] { "-n", "--account-name" })
            {
                Description = "Storage account name, must be in public azure cloud.",
                Required = true
            };

        private static Option<string> AzureStorageAccountKeyOption() =>
            new Option<string>(name: "client-id", aliases: new[] { "-k", "--client-id" })
            {
                Description = "Identity Client ID. If left blank, ambient identity will be used.",
                DefaultValueFactory = _ => null,
                Required = true
            };

        private static Option<string> AzureStorageContainerNameOption() =>
            new Option<string>(name: "container-name", aliases: new[] { "-c", "--container-name" })
            {
                Description = "Storage account container name where the files will be uploaded.",
                DefaultValueFactory = _ => "dotnet-monitor"
            };

        private static Option<int> AzureStorageSasExpirationOption() =>
            new Option<int>(name: "sas-valid-days", aliases: new[] { "--sas-valid-days" })
            {
                Description = "Number of days to allow access to the blobs via the provided SAS URIs.",
                DefaultValueFactory = _ => 1
            };
    }
}
