// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using DiagnosticsReleaseTool.Impl;
using System.CommandLine;
using System.CommandLine.Parsing;
using System.IO;
using System.Threading;
using System.Threading.Tasks;

namespace DiagnosticsReleaseTool.CommandLine
{
    class DiagnosticsReleaseCommandLine
    {
        static async Task<int> Main(string[] args)
        {
            var parser = new CommandLineBuilder()
                .AddCommand(PrepareRelease().SetAction( (ParseResult r) => { r})
                .CancelOnProcessTermination()
                .UseDefaults()
                .Build();

            return await parser.InvokeAsync(args);
        }

        public static Command PrepareRelease() =>
            new Command(
                name: "prepare-release",
                description: "Given a darc drop, generates validated manifests and layouts to initiate a tool release.")
            {
                CommandHandler.Create<Config, bool, bool, CancellationToken>(DiagnosticsReleaseRunner.PrepareRelease),
                
                // Inputs
                InputDropPathOption(), ToolManifestPathOption(), ReleaseNameOption(), BuildVersionOption(),
                // Toggles
                ToolManifestVerificationOption(), DiagnosticLoggingOption(), DryRunOption(),
                // Outputs
                StagingPathOption(), AzureStorageAccountNameOption(), AzureStorageAccountKeyOption(), AzureStorageContainerNameOption(), AzureStorageSasExpirationOption()
            };

        private static Option<bool> DiagnosticLoggingOption() =>
            new Option<bool>(name: "verbse",
                aliases: new[] { "-v" })
            {
                Description = "Enables diagnostic logging",
                DefaultValueFactory = _ => false
            };

        private static Option<bool> DryRunOption() =>
            new Option<bool>("dry-run")
            {
                Description = "Stages files and generates manifest, but does not publish.",
                DefaultValueFactory = _ => false
            };

        private static Option ToolManifestPathOption() =>
            new Option<FileInfo>("tool-manifest",
                aliases: new[] { "-t" })

            {
                Required = true,
                Description = "Full path to the manifest of tools and packages to publish.")
            }.AcceptExistingOnly();

        private static Option<string> ReleaseNameOption() =>
            new Option<string>(
                aliases: new[] { "-r", "--release-name" },
                description: "Name of this release.")
            {
                Required = true,
            };

        private static Option<string> BuildVersionOption() =>
            new Option<string>(
                aliases: new[] { "--build-version" },
                description: "Non-final version of the build.")
            {
                Required = true,
            };

        private static Option<bool> ToolManifestVerificationOption() =>
            new Option<bool>(
                alias: "--verify-tool-manifest",
                description: "Verifies that the assets being published match the manifest",
                getDefaultValue: () => true);

        private static Option<DirectoryInfo> InputDropPathOption() =>
            new Option<DirectoryInfo>(
                aliases: new[] { "-i", "--input-drop-path" },
                description: "Path to drop generated by `darc gather-drop`")
            {
                Required = true
            }.ExistingOnly();

        private static Option StagingPathOption() =>
            new Option<DirectoryInfo>(
                aliases: new[] { "--staging-directory", "-s" },
                description: "Full path to the staging path.",
                getDefaultValue: () => new DirectoryInfo(
                    Path.Join(Path.GetTempPath(), Path.GetRandomFileName())))
            .LegalFilePathsOnly();

        private static Option<string> AzureStorageAccountNameOption() =>
            new Option<string>(
                aliases: new[] { "-n", "--account-name" },
                description: "Storage account name, must be in public azure cloud.")
            {
                Required = true,
            };

        private static Option<string> AzureStorageAccountKeyOption() =>
            new Option<string>(
                aliases: new[] { "-k", "--client-id" },
                description: "Identity Client ID. If left blank, ambient identity will be used.",
                getDefaultValue: () => null)
            {
                Required = true,
            };

        private static Option<string> AzureStorageContainerNameOption() =>
            new Option<string>(
                aliases: new[] { "-c", "--container-name" },
                description: "Storage account container name where the files will be uploaded.",
                getDefaultValue: () => "dotnet-monitor");

        private static Option<int> AzureStorageSasExpirationOption() =>
            new Option<int>(
                aliases: new[] { "--sas-valid-days" },
                description: "Number of days to allow access to the blobs via the provided SAS URIs.",
                getDefaultValue: () => 1);
    }
}
