name: 'Check markdown links'
on:
  pull_request:
    paths: ['**.md']
    branches: ['main']

permissions:
  pull-requests: read

jobs:
  check-markdown-links:
    name: 'Check markdown links'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
        with:
          persist-credentials: false

      - name: Check markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368
        with:
          config-file: .github/linters/check-markdown-links-config.json
          use-quiet-mode: 'yes'
          use-verbose-mode: 'no'
